### ISSUE TITLE
May I ask how do you find out these command code?

### ISSUE THREAD

**Issue by janzhen** [jrnelson90/tinderboxpedal#4]
Hi Justin, thanks for your excellent work. May I ask how do you find out these command codes?

```python
TONE_1 = "01fe000053fe1a000000000000000000f00124000138000000f779"
TONE_2 = "01fe000053fe1a000000000000000000f00123010138000001f779"
TONE_3 = "01fe000053fe1a000000000000000000f00125020138000002f779"
TONE_4 = "01fe000053fe1a000000000000000000f00120030138000003f779"
```

**Comment by jrnelson90** [comment]
> Hi Justin, thanks for your excellent work. May I ask how do you find out these command codes?
> 
> ```python
> TONE_1 = "01fe000053fe1a000000000000000000f00124000138000000f779"
> TONE_2 = "01fe000053fe1a000000000000000000f00123010138000001f779"
> TONE_3 = "01fe000053fe1a000000000000000000f00125020138000002f779"
> TONE_4 = "01fe000053fe1a000000000000000000f00120030138000003f779"
> ```

By packet sniffing the app's BT controls, just like how a universal remote learns your TVs IR controls
https://www.wireshark.org/

**Comment by janzhen** [comment]
@jrnelson90 Thank you. I didn't know Wireshark can also sniff Bluetooth.
